### ISSUE TITLE
[UI] can't convert full user balance with join()

### ISSUE THREAD

**Issue by marczeller** [dapphub/chai#7]
using the [chai.money](chai.money) UI, a user can't convert the "max" amount of his DAI balance.

![image](https://user-images.githubusercontent.com/21088542/70357547-73ba8580-1877-11ea-8313-0db424bd4a93.png)

Metamask displays very high gasLimit and warn for a throw.

**Comment by MrChico** [comment]
Hey @marczeller , thanks for the report. This is due to a rounding error, and is being tracked in this issue https://github.com/lucasvo/chui/issues/8

**Comment by MrChico** [comment]
Fixed and updated `chai.money`
