### ISSUE TITLE
Go into depths of the permit pattern

### ISSUE THREAD

**Issue by vongohren** [dapphub/chai#8]
Are you guys going to implement permit into the UI interface or do a write up on how to use it? Since you guys are writing this in about "Note that the interface at chai.money does not yet support gasless transfers, but we are working on a something that demonstrates the full power of the permit pattern. Stay tuned for updates!"

**Comment by MrChico** [comment]
There is now an implementation at https://stablecoin.services/ which offers gasless transfers of Chai
